// File generated by FlutterFire CLI (ajustado).
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Como usar:
/// await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions não configurado para web. Rode o FlutterFire CLI novamente para web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError('DefaultFirebaseOptions não configurado para macOS.');
      case TargetPlatform.windows:
        throw UnsupportedError('DefaultFirebaseOptions não configurado para Windows.');
      case TargetPlatform.linux:
        throw UnsupportedError('DefaultFirebaseOptions não configurado para Linux.');
      default:
        throw UnsupportedError('Plataforma não suportada.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhojCjrqaaVq7xTUjUQM_egRLG4sLL5Qg',
    appId: '1:232773821373:android:5eabf3bb0425855532e8d4',
    messagingSenderId: '232773821373',
    projectId: 'moveela-2fb74',
    storageBucket: 'moveela-2fb74.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWan5SWObwr1mqK8BUVGZIx-8viRv4bGY',
    appId: '1:232773821373:ios:f3f4e8f2c97f25e432e8d4',
    messagingSenderId: '232773821373',
    projectId: 'moveela-2fb74',
    storageBucket: 'moveela-2fb74.firebasestorage.app',
    iosClientId: '232773821373-7orog3rq3hiiefmhhlb5r0ce0e6656it.apps.googleusercontent.com',
    iosBundleId: 'com.example.moveEla',
  );
}
